### ISSUE TITLE
Provide constants(replace magic strings with strings in StringConstants class)

### ISSUE THREAD

**Issue by md1guy** [lv-381-java/Actent#35]
https://github.com/lv-381-java/Actent/blob/develop/src/main/java/com/softserve/actent/model/entity/Image.java

**Comment by Pitcity** [comment]
so you've decided to left StringConstant as .java class?

**Comment by md1guy** [comment]
> so you've decided to left StringConstant as .java class?

Yes, we have discussed that with @ViktoriyaRyazhska and each other and decided that this is better approach in our case, because we will have localization for client on client-side(react), and here we need this just for catching(console-logging atleast) error messages for us. We may additionally discuss/talk about that(on Monday, I guess?) if you still think this is a bad decision.
