### ISSUE TITLE
Annotations are reversed; we should have **many** MessageBody and **one** Image.

### ISSUE THREAD

**Issue by md1guy** [lv-381-java/Actent#38]
https://github.com/lv-381-java/Actent/blob/d08776f688bec863b5521e161d9d88a7794101fc/src/main/java/com/softserve/actent/model/entity/MessageBody.java#L34

https://github.com/lv-381-java/Actent/blob/d08776f688bec863b5521e161d9d88a7794101fc/src/main/java/com/softserve/actent/model/entity/Image.java#L40

**Comment by octap16** [comment]
Annotation is right. One MessageBody should have many Images

**Comment by md1guy** [comment]
It's many-to-many in this case, but I think that's not necessary — one image per message is good enough. Will talk about that tho
